### PR TITLE
T71: Close post button modal after making a new post

### LINKED ISSUE #71: PostButtonModal onClose not working
The `onClose` for `PostButtonModal` with the Navbar is not working when you submit a new post and you currently have to close the modal manually instead. When creating a new post, we should be closing the modal on the button click

### PR DESCRIPTION
**Pull request by christopherkinyua**
I managed to address the issue of the post-modal button not closing. I added an `onClose` prop to the `ComposePost` and passed the `setOpenModal` function into it to invoke the function after a post is made. I made it conditional to check if `onClose` is provided. I was thinking about other cases when the `ComposePost`is called but no `onClose` is needed. Anyway, PR is ready for your review

### CODE REVIEW

File: src/components/Posts/ComposePost.tsx [hunk 1]
```diff
@@ -10,6 +10,7 @@ import EmojiPickerIconButton from "../Common/EmojiPickerIconButton";
 
 type ComposePostProps = {
   placeholder: string;
+  onClose: () => void;
```
Comment (Dennull) [inline src/components/Posts/ComposePost.tsx]: Can we make this an optional prop instead? Like this
```suggestion
  onClose?: () => void;
```

File: src/components/Posts/ComposePost.tsx [hunk 2]
```diff
@@ -52,6 +53,9 @@ const ComposePost = ({ placeholder }: ComposePostProps) => {
           displayName: user.displayName,
         })
       );
+      if (onClose) {
+        onClose();
+      }
```
Comment (Dennull) [inline src/components/Posts/ComposePost.tsx]: If we make the prop optional you're right that we need an if check. However, we can simplify it using [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). This basically checks to see if the function is defined before running it, so it achieves the same thing as your if statement
```suggestion
      onClose?.()
```

File: src/pages/Timeline.tsx [hunk 3]
```diff
@@ -18,7 +18,7 @@ const Timeline = () => {
           <Typography sx={styles.headerTitle} variant="h2">
             Timeline
           </Typography>
-          <ComposePost placeholder="What's happening?" />
+          <ComposePost placeholder="What's happening?" onClose={() => {}} />
```
Comment (Dennull) [inline src/pages/Timeline.tsx]: If we make `onClose` an optional prop, we can delete this
```suggestion
          <ComposePost placeholder="What's happening?"/>
```

**Review by Dennull — CHANGES_REQUESTED** [review]

File: src/components/Posts/ComposePost.tsx (hunk 1 above)
Comment (christopherkinyua) [reply src/components/Posts/ComposePost.tsx]: Nice, so just adding a question mark before make it conditional? I have implemented the change

File: src/components/Posts/ComposePost.tsx (hunk 2 above)
Comment (christopherkinyua) [reply src/components/Posts/ComposePost.tsx]: Done done done

File: src/pages/Timeline.tsx (hunk 3 above)
Comment (christopherkinyua) [reply src/pages/Timeline.tsx]: Alright Cap, done

File: src/components/Posts/ComposePost.tsx (hunk 1 above)
Comment (Dennull) [reply src/components/Posts/ComposePost.tsx]: Nice. And yes it makes an optional type. It's basically the same as `() => void | undefined`, so the onClose property is allowed to be undefined

**Review by Dennull — APPROVED** [review]
