### PR TITLE
T87: Fix reply order bug

### LINKED ISSUE #87: Reply order glitch
Problem:

Currently replies are sorted by likes, but when posts have the same amount of likes there's no "tiebreaker" to sort them by, so it seems as if they are ordered randomly 

Image

Solution:

It was decided that we should continue sorting replies by likes then sort by timestamp (descending) after. So, if a post has the same amount of likes as another post, they will be sorted from most recent to least recent

### PR DESCRIPTION
**Pull request by Dennull**
Resolves #87. Replies are now sorted by likes and then timestamp

### CODE REVIEW

File: src/components/Posts/ExpandedPostReplies.tsx [hunk 1]
```diff
@@ -22,22 +22,23 @@ const ExpandedPostReplies = ({ post }: ExpandedPostRepliesProps) => {
           {
             params: {
               userId: user.userId,
-              postId: post.postId,
+              postId: postId,
             },
           }
         );
         dispatch(setPosts(resultReplies.data as Post[]));
+        console.log(resultReplies);
```
Comment (NasihNazeem) [inline src/components/Posts/ExpandedPostReplies.tsx]: Think we just need this console.log removed

**Review by NasihNazeem — APPROVED** [review]

File: src/components/Posts/ExpandedPostReplies.tsx (hunk 1 above)
Comment (Dennull) [reply src/components/Posts/ExpandedPostReplies.tsx]: Nice catch, thanks!
